/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biz;

import org.biz.invoicesystem.entity.master.Item;
import org.biz.invoicesystem.entity.master.UOM;

/**
 *
 * @author d
 */
public class TableDataEditor extends javax.swing.JPanel {

    /**
     * Creates new form TableDataEditor
     */
    public TableDataEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lineDetailPanel = new org.components.containers.CPanel();
        tqty = new org.components.controls.CTextField();
        titem = new com.components.custom.TextFieldWithPopUP<Item>();
        tuom = new com.components.custom.TextFieldWithPopUP<UOM>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLine = new org.components.controls.ModelEditableTable();
        gridControllerPanel1 = new com.components.custom.GridControllerPanel();

        setLayout(null);

        lineDetailPanel.setBackground(new java.awt.Color(153, 255, 0));
        lineDetailPanel.setLayout(null);

        tqty.setText("Qty");
        lineDetailPanel.add(tqty);
        tqty.setBounds(340, 10, 130, 30);

        titem.setText("Item");
        lineDetailPanel.add(titem);
        titem.setBounds(40, 10, 150, 30);

        tuom.setText("Unit");
        lineDetailPanel.add(tuom);
        tuom.setBounds(200, 10, 130, 30);

        add(lineDetailPanel);
        lineDetailPanel.setBounds(10, 80, 650, 50);

        tblLine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblLine);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 150, 720, 219);
        add(gridControllerPanel1);
        gridControllerPanel1.setBounds(740, 150, 90, 230);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.components.custom.GridControllerPanel gridControllerPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.components.containers.CPanel lineDetailPanel;
    private org.components.controls.ModelEditableTable tblLine;
    private com.components.custom.TextFieldWithPopUP<Item> titem;
    private org.components.controls.CTextField tqty;
    private com.components.custom.TextFieldWithPopUP<UOM> tuom;
    // End of variables declaration//GEN-END:variables
}
