/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.components.controls;

import javax.swing.JMenuItem;

/**
 *
 * @author jawa
 */
public class MenuItemComponent extends JMenuItem {

    
    private Object busObj;

    public Object getBusObj() {
        return busObj;
    }

    public void setBusObj(Object busObj) {
        this.busObj = busObj;
    }
    
    
    /**
     * Creates new form MenuItem
     */
    public MenuItemComponent() {
        initComponents();
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
