/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.biz.invoicesystem.ui.transactions;

import org.biz.app.ui.util.Command;
import org.biz.invoicesystem.service.master.CategoryService;

/**
 *
 * @author Jawad
 */
public class CategoryTab extends javax.swing.JPanel {


    /**
     * Creates new form CategoryTab
     */
    public CategoryTab() {
        initComponents();
        mytsk.start();
    }
    
    Command mytsk = new Command() {

        public Object doBackgroundTask() {
            CategoryService categoryService = new CategoryService();
            return categoryService;
        }

        public void doResultTask(Object obj) {
            CategoryService categoryService = (CategoryService) obj;
            categoryUI1.config();
            categoryUI1.setService(categoryService);
//            crudcontrolPanel.setCrudController(categoryUI1);
            categoryListUI1.config();
            categoryListUI1.setService(categoryService);
            categoryListUI1.setDetailPanel(categoryUI1);

        }

    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryUI1 = new org.biz.master.ui.CategoryUI();
        categoryListUI1 = new org.biz.invoicesystem.ui.list.master.CategoryListUI();

        javax.swing.GroupLayout categoryUI1Layout = new javax.swing.GroupLayout(categoryUI1);
        categoryUI1.setLayout(categoryUI1Layout);
        categoryUI1Layout.setHorizontalGroup(
            categoryUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1302, Short.MAX_VALUE)
        );
        categoryUI1Layout.setVerticalGroup(
            categoryUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout categoryListUI1Layout = new javax.swing.GroupLayout(categoryListUI1);
        categoryListUI1.setLayout(categoryListUI1Layout);
        categoryListUI1Layout.setHorizontalGroup(
            categoryListUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        categoryListUI1Layout.setVerticalGroup(
            categoryListUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoryUI1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(categoryListUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(categoryUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryListUI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.biz.invoicesystem.ui.list.master.CategoryListUI categoryListUI1;
    private org.biz.master.ui.CategoryUI categoryUI1;
    // End of variables declaration//GEN-END:variables
}
