/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.biz.invoicesystem.ui.transactions;

import org.components.windows.DetailPanel;
import org.components.windows.MasterViewUI;
import org.components.windows.UIFrame;

/**
 *
 * @author Jawad
 */
public class GRNFrame extends UIFrame{

    /**
     * Creates new form GRNFrame
     */
    public GRNFrame() {
      
         super();
        initComponents();
        setTabbedPane(jTabbedPane1);
        
    }
    
    
        
    public MasterViewUI getMaster() {
        return gDNListV11;
    }

    public DetailPanel getDetail() {
        return gDNV11;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        gDNV11 = new org.biz.invoicesystem.ui.transactions.GDNV1();
        gDNListV11 = new org.biz.invoicesystem.ui.transactions.GDNListV1();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout gDNV11Layout = new javax.swing.GroupLayout(gDNV11);
        gDNV11.setLayout(gDNV11Layout);
        gDNV11Layout.setHorizontalGroup(
            gDNV11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gDNV11Layout.setVerticalGroup(
            gDNV11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RO", gDNV11);

        javax.swing.GroupLayout gDNListV11Layout = new javax.swing.GroupLayout(gDNListV11);
        gDNListV11.setLayout(gDNListV11Layout);
        gDNListV11Layout.setHorizontalGroup(
            gDNListV11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1267, Short.MAX_VALUE)
        );
        gDNListV11Layout.setVerticalGroup(
            gDNListV11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ROList", gDNListV11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1272, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.biz.invoicesystem.ui.transactions.GDNListV1 gDNListV11;
    private org.biz.invoicesystem.ui.transactions.GDNV1 gDNV11;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
