/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.biz.invoicesystem.ui.transactions;

import org.biz.invoicesystem.service.master.WareHouseService;

/**
 *
 * @author Jawad
 */
public class WareHouseTab extends javax.swing.JPanel {
 WareHouseService whs = new WareHouseService();
    
    /**
     * Creates new form WareHouseTab
     */
    public WareHouseTab() {
        initComponents();
          wareHouseUI1.config();
        wareHouseUI1.setService(whs);
        crudcontrolPanel.setCrudController(wareHouseUI1);
        wareHouseListUI1.config();
        wareHouseListUI1.setService(whs);
        wareHouseListUI1.setDetailPanel(wareHouseUI1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wareHouseUI1 = new org.biz.erp.inventory.ui.WareHouseUI();
        wareHouseListUI1 = new org.biz.erp.inventory.ui.list.WareHouseListUI();
        crudcontrolPanel = new com.components.custom.ControlPanel();

        javax.swing.GroupLayout wareHouseUI1Layout = new javax.swing.GroupLayout(wareHouseUI1);
        wareHouseUI1.setLayout(wareHouseUI1Layout);
        wareHouseUI1Layout.setHorizontalGroup(
            wareHouseUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
        );
        wareHouseUI1Layout.setVerticalGroup(
            wareHouseUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout wareHouseListUI1Layout = new javax.swing.GroupLayout(wareHouseListUI1);
        wareHouseListUI1.setLayout(wareHouseListUI1Layout);
        wareHouseListUI1Layout.setHorizontalGroup(
            wareHouseListUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        wareHouseListUI1Layout.setVerticalGroup(
            wareHouseListUI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wareHouseListUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wareHouseUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crudcontrolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(crudcontrolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wareHouseUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wareHouseListUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected com.components.custom.ControlPanel crudcontrolPanel;
    private org.biz.erp.inventory.ui.list.WareHouseListUI wareHouseListUI1;
    private org.biz.erp.inventory.ui.WareHouseUI wareHouseUI1;
    // End of variables declaration//GEN-END:variables
}
