/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.components.windows;

import app.utils.SystemUtil;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.biz.dao.service.Service;
import org.components.controls.CxTable;
import org.components.test.ResultPage;

/**
 *
 * @author d
 */
public class ListViewPanel<T> extends TabPanelUI implements ListSelectionListener{
    
    protected UIController controller;
    
    public void setController(UIController controller){
        this.controller = controller;
    } 
    /**
     * Creates new form ListViewPanel
     */
    public ListViewPanel() {
        super();
//        initComponents();
    }

    @Override
    public void init() {
//        initComponents();
        super.init();
        if(listUI==null)return;        
        listUI.setSearchQueryUI(searchQueryUI);
         if(searchQueryUI!=null){
        searchQueryUI.setListView(listUI);
         }        
        init(listUI.getTable());
    }

    @Override
    public void setService(Service service) {
        super.setService(service);
        if (searchQueryUI != null) {
            searchQueryUI.setServiceForQuery(service);            
        }
    }

    private DetailPanel dp;
    
    public void setDetailPanel(DetailPanel de){        
    this.dp=de;
    }
    
    public DetailPanel getDetailPanel(){
    return dp;
    }
            
    
    public void init(final CxTable tbl) {
        if (tbl == null) {
            return;
        }
        tbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    Object obj = tbl.getSelectedObject();
                    if (obj == null) {
                        return;
                    }
                   if(dp!=null){
                    dp.setSelectedBusObj(obj);
                    dp.setBusObject(obj);
                    SystemUtil.bringTabToFront(dp);
                }
                }
            }
        });
        
    }

    @Override
    public void updateEntityUI() {
    
        SystemUtil.setTools(null);
        
    }
  
    
    public void setResultPage(ResultPage res){
        listUI.setResult(res);        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchQueryUI = new org.components.windows.SearchQueryUIPanel();
        listUI = new org.components.windows.ListViewUI();

        javax.swing.GroupLayout searchQueryUILayout = new javax.swing.GroupLayout(searchQueryUI);
        searchQueryUI.setLayout(searchQueryUILayout);
        searchQueryUILayout.setHorizontalGroup(
            searchQueryUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        searchQueryUILayout.setVerticalGroup(
            searchQueryUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchQueryUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listUI, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchQueryUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listUI, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected org.components.windows.ListViewUI listUI;
    protected org.components.windows.SearchQueryUIPanel searchQueryUI;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
      
       
       
    }
    
    public ListViewUI getListViewUI(){
    return listUI;
    }
}
