/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.components.windows;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.biz.app.ui.util.StringUtility;
import org.components.containers.CPanel;

/**
 *
 * @author jawa
 */
public class UIFrame extends javax.swing.JFrame {

    
    private UIController controller;
    protected JTabbedPane tabbedPane;
    /**
     * Creates new form UIFrame
     */
    public UIFrame() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        initComponents();
//        setFocusTraversalPolicy(new MyFocusPolicy());
        
        addWindowFocusListener(new WindowAdapter() {

            @Override
            public void windowGainedFocus(WindowEvent e) {
                
                //focus to first component                 
                 if(tabbedPane.getSelectedComponent() instanceof CPanel){
                     ((CPanel)tabbedPane.getSelectedComponent()).requestFocus();
                 } 
                 
            }
        
        });

    }

    
    public void setController( UIController controller ){
        this.controller = controller;
    }
    
    public void setTabbedPane(JTabbedPane pane){
       this.tabbedPane =  pane;
       tabbedPane.addChangeListener(new ChangeListener() {

           @Override
           public void stateChanged(ChangeEvent e) {
               
           }
       });
    }
    
    public void goToDetail(){   
        Object [] lst =tabbedPane.getComponents();
        for(Object obj :lst){
            if(obj instanceof DetailPanel && getDetail() == obj){
                tabbedPane.setSelectedComponent(getDetail());
            }
            
        }
    }
    
    public void goToList() {
        Object[] lst = tabbedPane.getComponents();
        for (Object obj : lst) {
            if (obj instanceof ListViewUI && StringUtility.containsStringIgnoreCase("List", ((DetailPanel) obj).getTabName())) {
                tabbedPane.setSelectedComponent((DetailPanel) obj);
            }

        }
    }
    
    
    public MasterViewUI getMaster(){
    return null;
    }
    
    public DetailPanel getDetail(){
    return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
