/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biz.invoicesystem.ui.list.master;

import org.biz.app.ui.util.QueryManager;
import org.biz.dao.service.CQuery;
import org.components.windows.SearchQueryUIPanel;

/**
 *
 * @author jawath
 */
public class CategorySUI extends SearchQueryUIPanel {

    /**
     * Creates new form CategorySUI
     */
    public CategorySUI() {
        super();
        initComponents();
        init();
        qms=qm;
    }
    
    
    
   public void increaseWidth(){
       System.out.println("nothing tho print "
               + "");
       System.out.println("exceuting system comands t0o override the execuation methods"
               + "");
       System.out.println("simple tent a4f"  );
       System.out.println("laptop maniac i am not a moron"
               + "go through the code "+
               .20
               
               
               );
   
   }
   
   QueryManager qm=new QueryManager() {

            @Override
            public CQuery getCQuery() {
                if(getService()==null)return null;
                
                return getService().getDao().getAllQuery();
            }

        @Override
        public CQuery getCountQuery() {
            
            return getService().getDao().getAllCountQuery();
        }
            
            
        
        };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
