/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test.test;

import java.util.List;
import org.biz.app.ui.util.QueryManager;
import org.biz.invoicesystem.service.master.CategoryService;
import org.components.test.ResultPage;
import org.components.windows.ListViewUI;

/**
 *
 * @author Jawad
 */
public class TestListUI extends ListViewUI {

    /**
     * Creates new form TestListUI
     */
    public TestListUI() {
        super();
        super.initPaging(new myx());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

 CategoryService cs = new CategoryService();

 class myx extends QueryManager {

        @Override
        public Long executeCountQuery() {
           
            return (long)cs.getDao().getAllCount(); 
        }

        @Override
        public List executeQuery(int page) {
           return cs.getDao().getAll(page);
       
        }

        @Override
        public void postQuery(Object objs) {
//            super.postQuery(objs);
            
            System.out.println("List data");
            tbl.setModelCollection((List)((ResultPage)objs).getResult());
            
        }
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
