/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biz.erp.inventory.ui.list;

import org.biz.invoicesystem.entity.master.Warehouse;
import org.components.windows.ListViewPanel;

/**
 *
 * @author d
 */
public class WareHouseListUI extends ListViewPanel<Warehouse> {

    /**
     * Creates new form WareHouseListUI
     */
    public WareHouseListUI() {
//        initComponents();
        super();
    }

    @Override
    public void init() {
        initComponents();      
        listUI = wareHoueLV1;
        searchQueryUI = wareHouseSearchQueryUIPanel1;
        super.init();         

  
        //set query manager for pagination
    }
    




    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wareHoueLV1 = new org.biz.erp.inventory.ui.list.WareHoueLV();
        wareHouseSearchQueryUIPanel1 = new org.biz.erp.inventory.ui.list.WareHouseSUI();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wareHoueLV1, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                    .addComponent(wareHouseSearchQueryUIPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(wareHouseSearchQueryUIPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wareHoueLV1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.biz.erp.inventory.ui.list.WareHoueLV wareHoueLV1;
    private org.biz.erp.inventory.ui.list.WareHouseSUI wareHouseSearchQueryUIPanel1;
    // End of variables declaration//GEN-END:variables
}
