/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.biz.erp.inventory.ui.list;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import org.biz.app.ui.util.QueryManager;
import org.biz.dao.service.CQuery;
import org.biz.invoicesystem.service.master.WareHouseService;
import org.components.windows.SearchQueryUIPanel;

/**
 *
 * @author jawath
 */
public class WareHouseSUI extends SearchQueryUIPanel {

    private WareHouseService whs = new WareHouseService();
    /**
     * Creates new form SearchQueryUIPanel
     */
    public WareHouseSUI() {
        super();
        initComponents();
        qms=qm;
        tsearch.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                
                //execute the query 
                
                // 1) create the query 
                // 2) execute the query 
                //3) set the result tof ui
                
                
            }       
        });
        //
    }
    
    QueryManager qm = new QueryManager() {

        @Override
        public CQuery getCQuery() {
//                if(getService()==null)return null;

            return whs.getDAO().getQueryByCodeLike(tsearch.getText());
        }

        public CQuery getCountQuery() {

            return whs.getDAO().getCountQueryByCodeLike(tsearch.getText());
        }

    };


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tsearch = new javax.swing.JTextField();

        jLabel1.setText("Enter WareHouse detail: -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables

}
